# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Nathan Owsiany
tagline:          'A journey to full-stack development.'
description:      "I'm just some dude... I like to learn."
url:              http://nathan.owsiany.me

author:
  name:           'Nathan Owsiany'
  url:            https://twitter.com/nathanows

paginate:         5

# Custom vars
version:          1.1

github:
  repo:           https://github.com/ndwhtlssthr/ndwhtlssthr.github.io