# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Nathan Owsiany
tagline:          'The personal blog of Nathan Owsiany'
description:      'The personal blog of Nathan Owsiany.'
url:              http://nathan.owsiany.me

author:
  name:           'Nathan Owsiany'
  url:            https://twitter.com/nathanows

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/ndwhtlssthr/ndwhtlssthr.github.io